version:'3'

services:
  mongo: mongo
  container_name: mongo
  restart: always
  ports:
    - "27017:27017"

  volumes:
    - ~/Descktop/nodeJs_mongoDB/data/db
  networks:
    - mongo-network


mongo-express:
  image: mongo-express:0.54
  container_name: mongo-express
  ports: 
    - 8081:8081
  depends_on:
    - mongo
  environment:
    ME_CONFIG_BASICAUTH_USERNAME: root
    ME_CONFIG_BASICAUTH_PASSWORD: root
    ME_CONFIG_MONGODB_PORT: 27017
    ME_CONFIG_MONGODB_ADMINUSERNAME: root
    ME_CONFIG_MONGODB_ADMINPASSWORD: root
  link:
    - mongo
  networks:
    - mongo-network

networks:
  mongo-network:
    driver: bridge
    